export const CAR_IMAGES: any = {
    "audi_a6.jpg": require("../../assets/car-images/audi_a6.jpg"),
    "bwm_7.jpg": require("../../assets/car-images/bwm_7.jpg"),
    "chevrolet_silverado.jpg": require("../../assets/car-images/chevrolet_silverado.jpg"),
    "ford_explorer.jpg": require("../../assets/car-images/ford_explorer.jpg"),
    "honda_civic.jpg": require("../../assets/car-images/honda_civic.jpg"),
    "hyundai_santa_fe.jpg": require("../../assets/car-images/hyundai_santa_fe.jpg"),
    "jeep_wrangler.jpg": require("../../assets/car-images/jeep_wrangler.jpg"),
    "kia_soul.jpg": require("../../assets/car-images/kia_soul.jpg"),
    "mercedes_benz_e_class.jpg": require("../../assets/car-images/mercedes_benz_e_class.jpg"),
    "nissan_altima.jpg": require("../../assets/car-images/nissan_altima.jpg"),
    "subaru_outback.jpeg": require("../../assets/car-images/subaru_outback.jpeg"),
    "tesla_model_3.jpg": require("../../assets/car-images/tesla_model_3.jpg"),
    "toyota_corolla.jpg": require("../../assets/car-images/toyota_corolla.jpg"),
    "volkswagen_golf.jpg": require("../../assets/car-images/volkswagen_golf.jpg"),
    "ford_mustang.jpg": require("../../assets/car-images/ford_mustang.jpg"),
}