INSERT INTO cars (manufacturer, model, seats_number, car_type, color, price_per_day, transmission_type, file_name)
VALUES ('Toyota', 'Corolla', 5, 'SEDAN', 'Blue', 50, 'AUTOMATIC', 'toyota_corolla.jpg'),
       ('Ford', 'Mustang', 2, 'SPORT', 'Red', 80, 'MANUAL', 'ford_mustang.jpg'),
       ('Honda', 'Civic', 5, 'SEDAN', 'Silver', 45, 'AUTOMATIC', 'honda_civic.jpg'),
       ('Chevrolet', 'Silverado', 5, 'PICKUP', 'Black', 70, 'AUTOMATIC', 'chevrolet_silverado.jpg'),
       ('Volkswagen', 'Golf', 5, 'HATCHBACK', 'White', 55, 'MANUAL', 'volkswagen_golf.jpg'),
       ('Nissan', 'Altima', 5, 'SEDAN', 'Gray', 48, 'AUTOMATIC', 'nissan_altima.jpg'),
       ('BMW', '7 Series', 5, 'LUXURY', 'Black', 90, 'AUTOMATIC', 'bwm_7.jpg'),
       ('Hyundai', 'Santa Fe', 7, 'SUV', 'Blue', 75, 'AUTOMATIC', 'hyundai_santa_fe.jpg'),
       ('Audi', 'A6', 5, 'LUXURY', 'Silver', 85, 'AUTOMATIC', 'audi_a6.jpg'),
       ('Jeep', 'Wrangler', 4, 'OFF_ROAD', 'Green', 70, 'MANUAL', 'jeep_wrangler.jpg'),
       ('Subaru', 'Outback', 5, 'CROSSOVER', 'White', 60, 'AUTOMATIC', 'subaru_outback.jpeg'),
       ('Mercedes-Benz', 'E-Class', 5, 'LUXURY', 'Gray', 95, 'AUTOMATIC', 'mercedes_benz_e_class.jpg'),
       ('Kia', 'Soul', 5, 'COMPACT', 'Red', 50, 'AUTOMATIC', 'kia_soul.jpg'),
       ('Ford', 'Explorer', 7, 'SUV', 'Silver', 80, 'AUTOMATIC', 'ford_explorer.jpg'),
       ('Tesla', 'Model 3', 5, 'ELECTRIC', 'Blue', 100, 'AUTOMATIC', 'tesla_model_3.jpg');
