INSERT INTO cars (manufacturer, model, seats_number, car_type, color, price_per_day, transmission_type)
VALUES ('Toyota', 'Corolla', 5, 'SEDAN', 'Blue', 50, 'AUTOMATIC'),
       ('Ford', 'Mustang', 2, 'SPORT', 'Red', 80, 'MANUAL'),
       ('Honda', 'Civic', 5, 'SEDAN', 'Silver', 45, 'AUTOMATIC'),
       ('Chevrolet', 'Silverado', 3, 'PICKUP', 'Black', 70, 'AUTOMATIC'),
       ('Volkswagen', 'Golf', 5, 'HATCHBACK', 'White', 55, 'MANUAL'),
       ('Nissan', 'Altima', 5, 'SEDAN', 'Gray', 48, 'AUTOMATIC'),
       ('BMW', '7 Series', 5, 'LUXURY', 'Black', 90, 'AUTOMATIC'),
       ('Hyundai', 'Santa Fe', 7, 'SUV', 'Blue', 75, 'AUTOMATIC'),
       ('Audi', 'A6', 5, 'LUXURY', 'Silver', 85, 'AUTOMATIC'),
       ('Jeep', 'Wrangler', 4, 'OFF_ROAD', 'Green', 70, 'MANUAL'),
       ('Subaru', 'Outback', 5, 'CROSSOVER', 'White', 60, 'AUTOMATIC'),
       ('Mercedes-Benz', 'E-Class', 5, 'LUXURY', 'Gray', 95, 'AUTOMATIC'),
       ('Kia', 'Soul', 5, 'COMPACT', 'Red', 50, 'AUTOMATIC'),
       ('Ford', 'Explorer', 7, 'SUV', 'Silver', 80, 'AUTOMATIC'),
       ('Tesla', 'Model 3', 5, 'ELECTRIC', 'Blue', 100, 'AUTOMATIC');
